[versions]
jdk = "21"

lombok = "1.18.38"
jackarta-annotation = "3.0.0"
# service APIs deps
common-api = "0.0.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jackarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jackarta-annotation" }

common-api = { module = "com.github.sibdevtools:api-common", version.ref = "common-api" }